<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <FFMPEG_WIN>c:\work\code\ffmpeg-n7.1.2-7-g24c44c34dc-win64-gpl-shared-7.1\</FFMPEG_WIN>
  </PropertyGroup>
  <PropertyGroup />
  <ItemDefinitionGroup />
  <ItemGroup>
    <BuildMacro Include="FFMPEG_WIN">
      <Value>$(FFMPEG_WIN)</Value>
    </BuildMacro>
  </ItemGroup>
</Project>